/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package produccion.vistas;

import controlador.configuracion.controladorconfiguracion;
import java.util.List;
import modelos.Desempeno;
import modelos.Empleado;

/**
 *
 * @author James
 */
public class MuestraDesempeno extends javax.swing.JInternalFrame {
    public static controladorconfiguracion miControlador = new controladorconfiguracion();
    /**
     * Creates new form MuestraDesempeno
     */
    public MuestraDesempeno(Empleado empleado) {
        initComponents();
        List<Desempeno> listaDesempenoTurno1 = miControlador.sacadesempeñoxemp(empleado.getIdempleado() , 1);
        List<Desempeno> listaDesempenoTurno2 = miControlador.sacadesempeñoxemp(empleado.getIdempleado() , 2);
        listaDesempenoTurno1.get(0).getActividad().getIdactividad();
        lblProdT1Horneado.setText(Float.toString(listaDesempenoTurno1.get(0).getProduccion()));
        lblProdT1Decorado.setText(Float.toString(listaDesempenoTurno1.get(1).getProduccion()));
        lblProdT1Relleno.setText(Float.toString(listaDesempenoTurno1.get(2).getProduccion()));
        lblProdT1Empaque.setText(Float.toString(listaDesempenoTurno1.get(3).getProduccion()));
        lblMermaT1Horneado.setText(Float.toString(listaDesempenoTurno1.get(0).getMerma()));
        lblMermaT1Decorado.setText(Float.toString(listaDesempenoTurno1.get(1).getMerma()));
        lblMermaT1Relleno.setText(Float.toString(listaDesempenoTurno1.get(2).getMerma()));
        lblMermaT1Empaque.setText(Float.toString(listaDesempenoTurno1.get(3).getMerma()));
        lblProdT2Horneado.setText(Float.toString(listaDesempenoTurno2.get(0).getProduccion()));
        lblProdT2Decorado.setText(Float.toString(listaDesempenoTurno2.get(1).getProduccion()));
        lblProdT2Relleno.setText(Float.toString(listaDesempenoTurno2.get(2).getProduccion()));
        lblProdT2Empaque.setText(Float.toString(listaDesempenoTurno2.get(3).getProduccion()));
        lblMermaT2Horneado.setText(Float.toString(listaDesempenoTurno2.get(0).getMerma()));
        lblMermaT2Decorado.setText(Float.toString(listaDesempenoTurno2.get(1).getMerma()));
        lblMermaT2Relleno.setText(Float.toString(listaDesempenoTurno2.get(2).getMerma()));
        lblMermaT2Empaque.setText(Float.toString(listaDesempenoTurno2.get(3).getMerma()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        lblProdT1Horneado = new javax.swing.JLabel();
        lblProdT2Horneado = new javax.swing.JLabel();
        lblMermaT1Horneado = new javax.swing.JLabel();
        lblMermaT2Horneado = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        lblProdT1Decorado = new javax.swing.JLabel();
        lblMermaT1Decorado = new javax.swing.JLabel();
        lblProdT2Decorado = new javax.swing.JLabel();
        lblMermaT2Decorado = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        lblProdT1Relleno = new javax.swing.JLabel();
        lblProdT2Relleno = new javax.swing.JLabel();
        lblMermaT1Relleno = new javax.swing.JLabel();
        lblMermaT2Relleno = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        lblProdT1Empaque = new javax.swing.JLabel();
        lblProdT2Empaque = new javax.swing.JLabel();
        lblMermaT1Empaque = new javax.swing.JLabel();
        lblMermaT2Empaque = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setTitle("Desempeño del trabajador");

        jLabel18.setText("Galletas Producidas Promedio");

        jLabel19.setText("Galletas Rotas Promedio");

        jLabel36.setText("Turno 1");

        jLabel37.setText("Turno 2");

        lblProdT1Horneado.setText("jLabel1");

        lblProdT2Horneado.setText("jLabel2");

        lblMermaT1Horneado.setText("jLabel3");

        lblMermaT2Horneado.setText("jLabel4");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel36)
                    .addComponent(lblProdT1Horneado)
                    .addComponent(lblMermaT1Horneado))
                .addGap(83, 83, 83)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMermaT2Horneado)
                    .addComponent(lblProdT2Horneado)
                    .addComponent(jLabel37))
                .addGap(40, 40, 40))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel37))
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(lblProdT1Horneado)
                    .addComponent(lblProdT2Horneado))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblMermaT1Horneado)
                    .addComponent(lblMermaT2Horneado))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Horneado", jPanel3);

        jLabel23.setText("Galletas Producidas Promedio");

        jLabel24.setText("Galletas Rotas Promedio");

        jLabel14.setText("Turno 1");

        jLabel15.setText("Turno 2");

        lblProdT1Decorado.setText("jLabel5");

        lblMermaT1Decorado.setText("jLabel6");

        lblProdT2Decorado.setText("jLabel7");

        lblMermaT2Decorado.setText("jLabel8");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel23)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(lblProdT1Decorado)
                    .addComponent(lblMermaT1Decorado))
                .addGap(75, 75, 75)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMermaT2Decorado)
                    .addComponent(lblProdT2Decorado)
                    .addComponent(jLabel15))
                .addGap(50, 50, 50))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(lblProdT1Decorado)
                    .addComponent(lblProdT2Decorado))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblMermaT1Decorado)
                    .addComponent(lblMermaT2Decorado))
                .addGap(33, 33, 33))
        );

        jTabbedPane1.addTab("Decorado", jPanel4);

        jLabel25.setText("Galletas Producidas Promedio");

        jLabel26.setText("Galletas Rotas Promedio");

        jLabel31.setText("Turno 1");

        jLabel33.setText("Turno 2");

        lblProdT1Relleno.setText("jLabel9");

        lblProdT2Relleno.setText("jLabel10");

        lblMermaT1Relleno.setText("jLabel11");

        lblMermaT2Relleno.setText("jLabel12");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(jLabel26))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel31)
                    .addComponent(lblProdT1Relleno)
                    .addComponent(lblMermaT1Relleno))
                .addGap(71, 71, 71)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMermaT2Relleno)
                    .addComponent(jLabel33)
                    .addComponent(lblProdT2Relleno))
                .addGap(48, 48, 48))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(jLabel33))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(lblProdT1Relleno)
                    .addComponent(lblProdT2Relleno))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(lblMermaT1Relleno)
                    .addComponent(lblMermaT2Relleno))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Relleno", jPanel5);

        jLabel27.setText("Galletas Producidas Promedio");

        jLabel28.setText("Galletas Rotas Promedio");

        jLabel34.setText("Turno 1");

        jLabel35.setText("Turno 2");

        lblProdT1Empaque.setText("jLabel13");

        lblProdT2Empaque.setText("jLabel16");

        lblMermaT1Empaque.setText("jLabel17");

        lblMermaT2Empaque.setText("jLabel20");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel34)
                    .addComponent(lblProdT1Empaque)
                    .addComponent(lblMermaT1Empaque))
                .addGap(76, 76, 76)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMermaT2Empaque)
                    .addComponent(jLabel35)
                    .addComponent(lblProdT2Empaque))
                .addGap(42, 42, 42))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel35))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(lblProdT1Empaque)
                    .addComponent(lblProdT2Empaque))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(lblMermaT1Empaque)
                    .addComponent(lblMermaT2Empaque))
                .addGap(34, 34, 34))
        );

        jTabbedPane1.addTab("Empaque", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblMermaT1Decorado;
    private javax.swing.JLabel lblMermaT1Empaque;
    private javax.swing.JLabel lblMermaT1Horneado;
    private javax.swing.JLabel lblMermaT1Relleno;
    private javax.swing.JLabel lblMermaT2Decorado;
    private javax.swing.JLabel lblMermaT2Empaque;
    private javax.swing.JLabel lblMermaT2Horneado;
    private javax.swing.JLabel lblMermaT2Relleno;
    private javax.swing.JLabel lblProdT1Decorado;
    private javax.swing.JLabel lblProdT1Empaque;
    private javax.swing.JLabel lblProdT1Horneado;
    private javax.swing.JLabel lblProdT1Relleno;
    private javax.swing.JLabel lblProdT2Decorado;
    private javax.swing.JLabel lblProdT2Empaque;
    private javax.swing.JLabel lblProdT2Horneado;
    private javax.swing.JLabel lblProdT2Relleno;
    // End of variables declaration//GEN-END:variables
}
