package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idcliente;
     private String razonsocial;
     private Long ruc;
     private String direccion;
     private Integer telefono;
     private String correo;
     private String dnicontacto;
     private String nombrecontacto;
     private Integer telefonocontacto;
     private int estado;
     private String direccion1;
     private Set facturas = new HashSet(0);
     private Set ventas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idcliente, int estado, String direccion1) {
        this.idcliente = idcliente;
        this.estado = estado;
        this.direccion1 = direccion1;
    }
    public Cliente(int idcliente, String razonsocial, Long ruc, String direccion, Integer telefono, String correo, String dnicontacto, String nombrecontacto, Integer telefonocontacto, int estado, String direccion1, Set facturas, Set ventas) {
       this.idcliente = idcliente;
       this.razonsocial = razonsocial;
       this.ruc = ruc;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
       this.dnicontacto = dnicontacto;
       this.nombrecontacto = nombrecontacto;
       this.telefonocontacto = telefonocontacto;
       this.estado = estado;
       this.direccion1 = direccion1;
       this.facturas = facturas;
       this.ventas = ventas;
    }
   
    public int getIdcliente() {
        return this.idcliente;
    }
    
    public void setIdcliente(int idcliente) {
        this.idcliente = idcliente;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public Long getRuc() {
        return this.ruc;
    }
    
    public void setRuc(Long ruc) {
        this.ruc = ruc;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getDnicontacto() {
        return this.dnicontacto;
    }
    
    public void setDnicontacto(String dnicontacto) {
        this.dnicontacto = dnicontacto;
    }
    public String getNombrecontacto() {
        return this.nombrecontacto;
    }
    
    public void setNombrecontacto(String nombrecontacto) {
        this.nombrecontacto = nombrecontacto;
    }
    public Integer getTelefonocontacto() {
        return this.telefonocontacto;
    }
    
    public void setTelefonocontacto(Integer telefonocontacto) {
        this.telefonocontacto = telefonocontacto;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public String getDireccion1() {
        return this.direccion1;
    }
    
    public void setDireccion1(String direccion1) {
        this.direccion1 = direccion1;
    }
    public Set getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Set facturas) {
        this.facturas = facturas;
    }
    public Set getVentas() {
        return this.ventas;
    }
    
    public void setVentas(Set ventas) {
        this.ventas = ventas;
    }




}


