package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Detalleventa generated by hbm2java
 */
public class Detalleventa  implements java.io.Serializable {


     private int iddetalleventa;
     private Venta venta;
     private Producto producto;
     private Date fecha;
     private float cantidad;
     private float preciounitario;
     private Set detallefacturas = new HashSet(0);

    public Detalleventa() {
    }

	
    public Detalleventa(int iddetalleventa, Venta venta, Producto producto, float cantidad, float preciounitario) {
        this.iddetalleventa = iddetalleventa;
        this.venta = venta;
        this.producto = producto;
        this.cantidad = cantidad;
        this.preciounitario = preciounitario;
    }
    public Detalleventa(int iddetalleventa, Venta venta, Producto producto, Date fecha, float cantidad, float preciounitario, Set detallefacturas) {
       this.iddetalleventa = iddetalleventa;
       this.venta = venta;
       this.producto = producto;
       this.fecha = fecha;
       this.cantidad = cantidad;
       this.preciounitario = preciounitario;
       this.detallefacturas = detallefacturas;
    }
   
    public int getIddetalleventa() {
        return this.iddetalleventa;
    }
    
    public void setIddetalleventa(int iddetalleventa) {
        this.iddetalleventa = iddetalleventa;
    }
    public Venta getVenta() {
        return this.venta;
    }
    
    public void setVenta(Venta venta) {
        this.venta = venta;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }
    public float getPreciounitario() {
        return this.preciounitario;
    }
    
    public void setPreciounitario(float preciounitario) {
        this.preciounitario = preciounitario;
    }
    public Set getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


