package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Factura generated by hbm2java
 */
public class Factura  implements java.io.Serializable {


     private int idfactura;
     private Cliente cliente;
     private Date fechaemision;
     private String direccionentrega;
     private Float pesototal;
     private float subtotal;
     private float igv;
     private float total;
     private int estado;
     private Set detallefacturas = new HashSet(0);

    public Factura() {
    }

	
    public Factura(int idfactura, Cliente cliente, Date fechaemision, float subtotal, float igv, float total, int estado) {
        this.idfactura = idfactura;
        this.cliente = cliente;
        this.fechaemision = fechaemision;
        this.subtotal = subtotal;
        this.igv = igv;
        this.total = total;
        this.estado = estado;
    }
    public Factura(int idfactura, Cliente cliente, Date fechaemision, String direccionentrega, Float pesototal, float subtotal, float igv, float total, int estado, Set detallefacturas) {
       this.idfactura = idfactura;
       this.cliente = cliente;
       this.fechaemision = fechaemision;
       this.direccionentrega = direccionentrega;
       this.pesototal = pesototal;
       this.subtotal = subtotal;
       this.igv = igv;
       this.total = total;
       this.estado = estado;
       this.detallefacturas = detallefacturas;
    }
   
    public int getIdfactura() {
        return this.idfactura;
    }
    
    public void setIdfactura(int idfactura) {
        this.idfactura = idfactura;
    }
    public Cliente getCliente() {
        return this.cliente;
    }
    
    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    public Date getFechaemision() {
        return this.fechaemision;
    }
    
    public void setFechaemision(Date fechaemision) {
        this.fechaemision = fechaemision;
    }
    public String getDireccionentrega() {
        return this.direccionentrega;
    }
    
    public void setDireccionentrega(String direccionentrega) {
        this.direccionentrega = direccionentrega;
    }
    public Float getPesototal() {
        return this.pesototal;
    }
    
    public void setPesototal(Float pesototal) {
        this.pesototal = pesototal;
    }
    public float getSubtotal() {
        return this.subtotal;
    }
    
    public void setSubtotal(float subtotal) {
        this.subtotal = subtotal;
    }
    public float getIgv() {
        return this.igv;
    }
    
    public void setIgv(float igv) {
        this.igv = igv;
    }
    public float getTotal() {
        return this.total;
    }
    
    public void setTotal(float total) {
        this.total = total;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getDetallefacturas() {
        return this.detallefacturas;
    }
    
    public void setDetallefacturas(Set detallefacturas) {
        this.detallefacturas = detallefacturas;
    }




}


