package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA



/**
 * Movsalidadetalle generated by hbm2java
 */
public class Movsalidadetalle  implements java.io.Serializable {


     private MovsalidadetalleId id;
     private Movimiento movimiento;
     private Productoxmovimiento productoxmovimiento;
     private float cantidad;

    public Movsalidadetalle() {
    }

    public Movsalidadetalle(MovsalidadetalleId id, Movimiento movimiento, Productoxmovimiento productoxmovimiento, float cantidad) {
       this.id = id;
       this.movimiento = movimiento;
       this.productoxmovimiento = productoxmovimiento;
       this.cantidad = cantidad;
    }
   
    public MovsalidadetalleId getId() {
        return this.id;
    }
    
    public void setId(MovsalidadetalleId id) {
        this.id = id;
    }
    public Movimiento getMovimiento() {
        return this.movimiento;
    }
    
    public void setMovimiento(Movimiento movimiento) {
        this.movimiento = movimiento;
    }
    public Productoxmovimiento getProductoxmovimiento() {
        return this.productoxmovimiento;
    }
    
    public void setProductoxmovimiento(Productoxmovimiento productoxmovimiento) {
        this.productoxmovimiento = productoxmovimiento;
    }
    public float getCantidad() {
        return this.cantidad;
    }
    
    public void setCantidad(float cantidad) {
        this.cantidad = cantidad;
    }




}


