package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA



/**
 * ProduccionxempleadoId generated by hbm2java
 */
public class ProduccionxempleadoId  implements java.io.Serializable {


     private int idproduccion;
     private int idasignacion;
     private int idempleado;

    public ProduccionxempleadoId() {
    }

    public ProduccionxempleadoId(int idproduccion, int idasignacion, int idempleado) {
       this.idproduccion = idproduccion;
       this.idasignacion = idasignacion;
       this.idempleado = idempleado;
    }
   
    public int getIdproduccion() {
        return this.idproduccion;
    }
    
    public void setIdproduccion(int idproduccion) {
        this.idproduccion = idproduccion;
    }
    public int getIdasignacion() {
        return this.idasignacion;
    }
    
    public void setIdasignacion(int idasignacion) {
        this.idasignacion = idasignacion;
    }
    public int getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(int idempleado) {
        this.idempleado = idempleado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ProduccionxempleadoId) ) return false;
		 ProduccionxempleadoId castOther = ( ProduccionxempleadoId ) other; 
         
		 return (this.getIdproduccion()==castOther.getIdproduccion())
 && (this.getIdasignacion()==castOther.getIdasignacion())
 && (this.getIdempleado()==castOther.getIdempleado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdproduccion();
         result = 37 * result + this.getIdasignacion();
         result = 37 * result + this.getIdempleado();
         return result;
   }   


}


