package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA



/**
 * Produccionxproducto generated by hbm2java
 */
public class Produccionxproducto  implements java.io.Serializable {


     private ProduccionxproductoId id;
     private Produccion produccion;
     private Asignacionxproducto asignacionxproducto;
     private float produccion_1;
     private float merma;

    public Produccionxproducto() {
    }

    public Produccionxproducto(ProduccionxproductoId id, Produccion produccion, Asignacionxproducto asignacionxproducto, float produccion_1, float merma) {
       this.id = id;
       this.produccion = produccion;
       this.asignacionxproducto = asignacionxproducto;
       this.produccion_1 = produccion_1;
       this.merma = merma;
    }
   
    public ProduccionxproductoId getId() {
        return this.id;
    }
    
    public void setId(ProduccionxproductoId id) {
        this.id = id;
    }
    public Produccion getProduccion() {
        return this.produccion;
    }
    
    public void setProduccion(Produccion produccion) {
        this.produccion = produccion;
    }
    public Asignacionxproducto getAsignacionxproducto() {
        return this.asignacionxproducto;
    }
    
    public void setAsignacionxproducto(Asignacionxproducto asignacionxproducto) {
        this.asignacionxproducto = asignacionxproducto;
    }
    public float getProduccion_1() {
        return this.produccion_1;
    }
    
    public void setProduccion_1(float produccion_1) {
        this.produccion_1 = produccion_1;
    }
    public float getMerma() {
        return this.merma;
    }
    
    public void setMerma(float merma) {
        this.merma = merma;
    }




}


