package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Productoxproveedor generated by hbm2java
 */
public class Productoxproveedor  implements java.io.Serializable {


     private ProductoxproveedorId id;
     private Proveedor proveedor;
     private Producto producto;
     private Float precio;
     private Integer cantidadmaxima;
     private Date fecha;

    public Productoxproveedor() {
    }

	
    public Productoxproveedor(ProductoxproveedorId id, Proveedor proveedor, Producto producto) {
        this.id = id;
        this.proveedor = proveedor;
        this.producto = producto;
    }
    public Productoxproveedor(ProductoxproveedorId id, Proveedor proveedor, Producto producto, Float precio, Integer cantidadmaxima, Date fecha) {
       this.id = id;
       this.proveedor = proveedor;
       this.producto = producto;
       this.precio = precio;
       this.cantidadmaxima = cantidadmaxima;
       this.fecha = fecha;
    }
   
    public ProductoxproveedorId getId() {
        return this.id;
    }
    
    public void setId(ProductoxproveedorId id) {
        this.id = id;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(Float precio) {
        this.precio = precio;
    }
    public Integer getCantidadmaxima() {
        return this.cantidadmaxima;
    }
    
    public void setCantidadmaxima(Integer cantidadmaxima) {
        this.cantidadmaxima = cantidadmaxima;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


