package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Rol generated by hbm2java
 */
public class Rol  implements java.io.Serializable {


     private int idrol;
     private String nombre;
     private String descripcion;
     private Integer estado;
     private Set usuarios = new HashSet(0);
     private Set vistaxrols = new HashSet(0);

    public Rol() {
    }

	
    public Rol(int idrol) {
        this.idrol = idrol;
    }
    public Rol(int idrol, String nombre, String descripcion, Integer estado, Set usuarios, Set vistaxrols) {
       this.idrol = idrol;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.estado = estado;
       this.usuarios = usuarios;
       this.vistaxrols = vistaxrols;
    }
   
    public int getIdrol() {
        return this.idrol;
    }
    
    public void setIdrol(int idrol) {
        this.idrol = idrol;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getVistaxrols() {
        return this.vistaxrols;
    }
    
    public void setVistaxrols(Set vistaxrols) {
        this.vistaxrols = vistaxrols;
    }




}


