package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoempleado generated by hbm2java
 */
public class Tipoempleado  implements java.io.Serializable {


     private int idtipoempleado;
     private String nombre;
     private Float sueldo;
     private Set empleados = new HashSet(0);

    public Tipoempleado() {
    }

	
    public Tipoempleado(int idtipoempleado) {
        this.idtipoempleado = idtipoempleado;
    }
    public Tipoempleado(int idtipoempleado, String nombre, Float sueldo, Set empleados) {
       this.idtipoempleado = idtipoempleado;
       this.nombre = nombre;
       this.sueldo = sueldo;
       this.empleados = empleados;
    }
   
    public int getIdtipoempleado() {
        return this.idtipoempleado;
    }
    
    public void setIdtipoempleado(int idtipoempleado) {
        this.idtipoempleado = idtipoempleado;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Float getSueldo() {
        return this.sueldo;
    }
    
    public void setSueldo(Float sueldo) {
        this.sueldo = sueldo;
    }
    public Set getEmpleados() {
        return this.empleados;
    }
    
    public void setEmpleados(Set empleados) {
        this.empleados = empleados;
    }




}


