package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Unidadmedida generated by hbm2java
 */
public class Unidadmedida  implements java.io.Serializable {


     private int idunidadmedida;
     private String descripcion;
     private String nombre;
     private Set productos = new HashSet(0);

    public Unidadmedida() {
    }

	
    public Unidadmedida(int idunidadmedida, String nombre) {
        this.idunidadmedida = idunidadmedida;
        this.nombre = nombre;
    }
    public Unidadmedida(int idunidadmedida, String descripcion, String nombre, Set productos) {
       this.idunidadmedida = idunidadmedida;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.productos = productos;
    }
   
    public int getIdunidadmedida() {
        return this.idunidadmedida;
    }
    
    public void setIdunidadmedida(int idunidadmedida) {
        this.idunidadmedida = idunidadmedida;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


