package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int idempleado;
     private Empleado empleado;
     private Rol rol;
     private String nombreusuario;
     private String password;
     private String correo;
     private Integer estado;
     private Set logs = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(int idempleado, Empleado empleado, Rol rol, String nombreusuario, String password) {
        this.idempleado = idempleado;
        this.empleado = empleado;
        this.rol = rol;
        this.nombreusuario = nombreusuario;
        this.password = password;
    }
    public Usuario(int idempleado, Empleado empleado, Rol rol, String nombreusuario, String password, String correo, Integer estado, Set logs) {
       this.idempleado = idempleado;
       this.empleado = empleado;
       this.rol = rol;
       this.nombreusuario = nombreusuario;
       this.password = password;
       this.correo = correo;
       this.estado = estado;
       this.logs = logs;
    }
   
    public int getIdempleado() {
        return this.idempleado;
    }
    
    public void setIdempleado(int idempleado) {
        this.idempleado = idempleado;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Rol getRol() {
        return this.rol;
    }
    
    public void setRol(Rol rol) {
        this.rol = rol;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Integer getEstado() {
        return this.estado;
    }
    
    public void setEstado(Integer estado) {
        this.estado = estado;
    }
    public Set getLogs() {
        return this.logs;
    }
    
    public void setLogs(Set logs) {
        this.logs = logs;
    }




}


