/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package produccion.vistas;

import java.util.ArrayList;
import java.util.List;
import javax.swing.table.AbstractTableModel;
import modelos.Empleado;

/**
 *
 * @author James
 */
public class EmpleadoNoAsignados extends javax.swing.JInternalFrame {
    private ArrayList<Empleado> listaEmpleados = null;
    /**
     * Creates new form EmpleadoNoAsignados
     */
    public EmpleadoNoAsignados(ArrayList<Empleado> listEmpleados) {
        initComponents();
        listaEmpleados = listEmpleados;
        tblTrabajadores.setModel(modeloTabla);
    }

    private AbstractTableModel modeloTabla = new AbstractTableModel() {
        private String[] cabeceras = {"Código", "Nombres y Apellidos"};

        @Override
        public int getRowCount() {
            return listaEmpleados.size();
        }

        @Override
        public int getColumnCount() {
            return cabeceras.length;
        }

        @Override
        public String getColumnName(int columna) {
            return cabeceras[columna];
        }

        @Override
        public Object getValueAt(int rowIndex, int columnIndex) {
            int codigo;
            String nombre;
            if (columnIndex == 0) {
                codigo = listaEmpleados.get(rowIndex).getIdempleado();
                return codigo;
            } else if (columnIndex == 1) {
                nombre = listaEmpleados.get(rowIndex).getNombre() + " ";
                nombre += listaEmpleados.get(rowIndex).getAppaterno() + " ";
                nombre += listaEmpleados.get(rowIndex).getApmaterno();
                return nombre;
            } 
            return null;
        }

        @Override
        public Class<?> getColumnClass(int columna) {
                return String.class;
        }

        @Override
        public boolean isCellEditable(int row, int col) {
            return false;
        }

        @Override
        public void setValueAt(Object aValue, int rowIndex, int columnIndex) {
  
        }
    };
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrabajadores = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setTitle("Tabla De Empleados No Asignados");

        tblTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblTrabajadores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblTrabajadoresMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblTrabajadores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblTrabajadoresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblTrabajadoresMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int row = tblTrabajadores.getSelectedRow();
            Empleado empleado = listaEmpleados.get(row);
            MuestraDesempeno muestraDesempeno = new MuestraDesempeno(empleado);
            getDesktopPane().add(muestraDesempeno);
            muestraDesempeno.setVisible(true);
        }
    }//GEN-LAST:event_tblTrabajadoresMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTrabajadores;
    // End of variables declaration//GEN-END:variables
}
