package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Desempeno generated by hbm2java
 */
public class Desempeno  implements java.io.Serializable {


     private DesempenoId id;
     private Actividad actividad;
     private Empleado empleado;
     private Turno turno;
     private Date fecha;
     private float produccion;
     private float merma;
     private int numdatos;

    public Desempeno() {
    }

    public Desempeno(DesempenoId id, Actividad actividad, Empleado empleado, Turno turno, Date fecha, float produccion, float merma, int numdatos) {
       this.id = id;
       this.actividad = actividad;
       this.empleado = empleado;
       this.turno = turno;
       this.fecha = fecha;
       this.produccion = produccion;
       this.merma = merma;
       this.numdatos = numdatos;
    }
   
    public DesempenoId getId() {
        return this.id;
    }
    
    public void setId(DesempenoId id) {
        this.id = id;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public Empleado getEmpleado() {
        return this.empleado;
    }
    
    public void setEmpleado(Empleado empleado) {
        this.empleado = empleado;
    }
    public Turno getTurno() {
        return this.turno;
    }
    
    public void setTurno(Turno turno) {
        this.turno = turno;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public float getProduccion() {
        return this.produccion;
    }
    
    public void setProduccion(float produccion) {
        this.produccion = produccion;
    }
    public float getMerma() {
        return this.merma;
    }
    
    public void setMerma(float merma) {
        this.merma = merma;
    }
    public int getNumdatos() {
        return this.numdatos;
    }
    
    public void setNumdatos(int numdatos) {
        this.numdatos = numdatos;
    }




}


