package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Igvt generated by hbm2java
 */
public class Igvt  implements java.io.Serializable {


     private int idigv;
     private Float porcentaje;
     private Date fechainiciovigencia;

    public Igvt() {
    }

	
    public Igvt(int idigv, Date fechainiciovigencia) {
        this.idigv = idigv;
        this.fechainiciovigencia = fechainiciovigencia;
    }
    public Igvt(int idigv, Float porcentaje, Date fechainiciovigencia) {
       this.idigv = idigv;
       this.porcentaje = porcentaje;
       this.fechainiciovigencia = fechainiciovigencia;
    }
   
    public int getIdigv() {
        return this.idigv;
    }
    
    public void setIdigv(int idigv) {
        this.idigv = idigv;
    }
    public Float getPorcentaje() {
        return this.porcentaje;
    }
    
    public void setPorcentaje(Float porcentaje) {
        this.porcentaje = porcentaje;
    }
    public Date getFechainiciovigencia() {
        return this.fechainiciovigencia;
    }
    
    public void setFechainiciovigencia(Date fechainiciovigencia) {
        this.fechainiciovigencia = fechainiciovigencia;
    }




}


