package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Maquina generated by hbm2java
 */
public class Maquina  implements java.io.Serializable {


     private int idmaquina;
     private Actividad actividad;
     private String descripcion;
     private String nombre;
     private int estado;
     private Set asignacionxempleados = new HashSet(0);

    public Maquina() {
    }

	
    public Maquina(int idmaquina, Actividad actividad, int estado) {
        this.idmaquina = idmaquina;
        this.actividad = actividad;
        this.estado = estado;
    }
    public Maquina(int idmaquina, Actividad actividad, String descripcion, String nombre, int estado, Set asignacionxempleados) {
       this.idmaquina = idmaquina;
       this.actividad = actividad;
       this.descripcion = descripcion;
       this.nombre = nombre;
       this.estado = estado;
       this.asignacionxempleados = asignacionxempleados;
    }
   
    public int getIdmaquina() {
        return this.idmaquina;
    }
    
    public void setIdmaquina(int idmaquina) {
        this.idmaquina = idmaquina;
    }
    public Actividad getActividad() {
        return this.actividad;
    }
    
    public void setActividad(Actividad actividad) {
        this.actividad = actividad;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getAsignacionxempleados() {
        return this.asignacionxempleados;
    }
    
    public void setAsignacionxempleados(Set asignacionxempleados) {
        this.asignacionxempleados = asignacionxempleados;
    }




}


