package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA



/**
 * MovsalidadetalleId generated by hbm2java
 */
public class MovsalidadetalleId  implements java.io.Serializable {


     private int idproducto;
     private int idmovimientos;
     private int idmovimientoe;

    public MovsalidadetalleId() {
    }

    public MovsalidadetalleId(int idproducto, int idmovimientos, int idmovimientoe) {
       this.idproducto = idproducto;
       this.idmovimientos = idmovimientos;
       this.idmovimientoe = idmovimientoe;
    }
   
    public int getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(int idproducto) {
        this.idproducto = idproducto;
    }
    public int getIdmovimientos() {
        return this.idmovimientos;
    }
    
    public void setIdmovimientos(int idmovimientos) {
        this.idmovimientos = idmovimientos;
    }
    public int getIdmovimientoe() {
        return this.idmovimientoe;
    }
    
    public void setIdmovimientoe(int idmovimientoe) {
        this.idmovimientoe = idmovimientoe;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MovsalidadetalleId) ) return false;
		 MovsalidadetalleId castOther = ( MovsalidadetalleId ) other; 
         
		 return (this.getIdproducto()==castOther.getIdproducto())
 && (this.getIdmovimientos()==castOther.getIdmovimientos())
 && (this.getIdmovimientoe()==castOther.getIdmovimientoe());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdproducto();
         result = 37 * result + this.getIdmovimientos();
         result = 37 * result + this.getIdmovimientoe();
         return result;
   }   


}


