package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Ordenproduccion generated by hbm2java
 */
public class Ordenproduccion  implements java.io.Serializable {


     private int idordenproduccion;
     private Date fechainicio;
     private Date fechafin;
     private Date fecharegistro;
     private int estado;
     private Set detalleordenproduccions = new HashSet(0);
     private Set asignacions = new HashSet(0);

    public Ordenproduccion() {
    }

	
    public Ordenproduccion(int idordenproduccion, Date fechainicio, Date fechafin, Date fecharegistro, int estado) {
        this.idordenproduccion = idordenproduccion;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
        this.fecharegistro = fecharegistro;
        this.estado = estado;
    }
    public Ordenproduccion(int idordenproduccion, Date fechainicio, Date fechafin, Date fecharegistro, int estado, Set detalleordenproduccions, Set asignacions) {
       this.idordenproduccion = idordenproduccion;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.fecharegistro = fecharegistro;
       this.estado = estado;
       this.detalleordenproduccions = detalleordenproduccions;
       this.asignacions = asignacions;
    }
   
    public int getIdordenproduccion() {
        return this.idordenproduccion;
    }
    
    public void setIdordenproduccion(int idordenproduccion) {
        this.idordenproduccion = idordenproduccion;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public Date getFecharegistro() {
        return this.fecharegistro;
    }
    
    public void setFecharegistro(Date fecharegistro) {
        this.fecharegistro = fecharegistro;
    }
    public int getEstado() {
        return this.estado;
    }
    
    public void setEstado(int estado) {
        this.estado = estado;
    }
    public Set getDetalleordenproduccions() {
        return this.detalleordenproduccions;
    }
    
    public void setDetalleordenproduccions(Set detalleordenproduccions) {
        this.detalleordenproduccions = detalleordenproduccions;
    }
    public Set getAsignacions() {
        return this.asignacions;
    }
    
    public void setAsignacions(Set asignacions) {
        this.asignacions = asignacions;
    }




}


