package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Productoxmovimiento generated by hbm2java
 */
public class Productoxmovimiento  implements java.io.Serializable {


     private ProductoxmovimientoId id;
     private Movimiento movimiento;
     private Producto producto;
     private Date fvencimiento;
     private float stock;
     private float stockactual;
     private Set movsalidadetalles = new HashSet(0);

    public Productoxmovimiento() {
    }

	
    public Productoxmovimiento(ProductoxmovimientoId id, Movimiento movimiento, Producto producto, Date fvencimiento, float stock, float stockactual) {
        this.id = id;
        this.movimiento = movimiento;
        this.producto = producto;
        this.fvencimiento = fvencimiento;
        this.stock = stock;
        this.stockactual = stockactual;
    }
    public Productoxmovimiento(ProductoxmovimientoId id, Movimiento movimiento, Producto producto, Date fvencimiento, float stock, float stockactual, Set movsalidadetalles) {
       this.id = id;
       this.movimiento = movimiento;
       this.producto = producto;
       this.fvencimiento = fvencimiento;
       this.stock = stock;
       this.stockactual = stockactual;
       this.movsalidadetalles = movsalidadetalles;
    }
   
    public ProductoxmovimientoId getId() {
        return this.id;
    }
    
    public void setId(ProductoxmovimientoId id) {
        this.id = id;
    }
    public Movimiento getMovimiento() {
        return this.movimiento;
    }
    
    public void setMovimiento(Movimiento movimiento) {
        this.movimiento = movimiento;
    }
    public Producto getProducto() {
        return this.producto;
    }
    
    public void setProducto(Producto producto) {
        this.producto = producto;
    }
    public Date getFvencimiento() {
        return this.fvencimiento;
    }
    
    public void setFvencimiento(Date fvencimiento) {
        this.fvencimiento = fvencimiento;
    }
    public float getStock() {
        return this.stock;
    }
    
    public void setStock(float stock) {
        this.stock = stock;
    }
    public float getStockactual() {
        return this.stockactual;
    }
    
    public void setStockactual(float stockactual) {
        this.stockactual = stockactual;
    }
    public Set getMovsalidadetalles() {
        return this.movsalidadetalles;
    }
    
    public void setMovsalidadetalles(Set movsalidadetalles) {
        this.movsalidadetalles = movsalidadetalles;
    }




}


