package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA



/**
 * Produccionxempleado generated by hbm2java
 */
public class Produccionxempleado  implements java.io.Serializable {


     private ProduccionxempleadoId id;
     private Produccion produccion;
     private Asignacionxempleado asignacionxempleado;
     private float produccion_1;
     private float merma;

    public Produccionxempleado() {
    }

    public Produccionxempleado(ProduccionxempleadoId id, Produccion produccion, Asignacionxempleado asignacionxempleado, float produccion_1, float merma) {
       this.id = id;
       this.produccion = produccion;
       this.asignacionxempleado = asignacionxempleado;
       this.produccion_1 = produccion_1;
       this.merma = merma;
    }
   
    public ProduccionxempleadoId getId() {
        return this.id;
    }
    
    public void setId(ProduccionxempleadoId id) {
        this.id = id;
    }
    public Produccion getProduccion() {
        return this.produccion;
    }
    
    public void setProduccion(Produccion produccion) {
        this.produccion = produccion;
    }
    public Asignacionxempleado getAsignacionxempleado() {
        return this.asignacionxempleado;
    }
    
    public void setAsignacionxempleado(Asignacionxempleado asignacionxempleado) {
        this.asignacionxempleado = asignacionxempleado;
    }
    public float getProduccion_1() {
        return this.produccion_1;
    }
    
    public void setProduccion_1(float produccion_1) {
        this.produccion_1 = produccion_1;
    }
    public float getMerma() {
        return this.merma;
    }
    
    public void setMerma(float merma) {
        this.merma = merma;
    }




}


