package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Proveedor generated by hbm2java
 */
public class Proveedor  implements java.io.Serializable {


     private int idproveedor;
     private String razonsocial;
     private String direccion;
     private Integer telefono;
     private String correo;
     private Integer dnicontacto;
     private String nombrecontacto;
     private Integer telefonocontacto;
     private Long ruc;
     private String estado;
     private Set productoxproveedors = new HashSet(0);
     private Set compras = new HashSet(0);

    public Proveedor() {
    }

	
    public Proveedor(int idproveedor) {
        this.idproveedor = idproveedor;
    }
    public Proveedor(int idproveedor, String razonsocial, String direccion, Integer telefono, String correo, Integer dnicontacto, String nombrecontacto, Integer telefonocontacto, Long ruc, String estado, Set productoxproveedors, Set compras) {
       this.idproveedor = idproveedor;
       this.razonsocial = razonsocial;
       this.direccion = direccion;
       this.telefono = telefono;
       this.correo = correo;
       this.dnicontacto = dnicontacto;
       this.nombrecontacto = nombrecontacto;
       this.telefonocontacto = telefonocontacto;
       this.ruc = ruc;
       this.estado = estado;
       this.productoxproveedors = productoxproveedors;
       this.compras = compras;
    }
   
    public int getIdproveedor() {
        return this.idproveedor;
    }
    
    public void setIdproveedor(int idproveedor) {
        this.idproveedor = idproveedor;
    }
    public String getRazonsocial() {
        return this.razonsocial;
    }
    
    public void setRazonsocial(String razonsocial) {
        this.razonsocial = razonsocial;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Integer getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(Integer telefono) {
        this.telefono = telefono;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public Integer getDnicontacto() {
        return this.dnicontacto;
    }
    
    public void setDnicontacto(Integer dnicontacto) {
        this.dnicontacto = dnicontacto;
    }
    public String getNombrecontacto() {
        return this.nombrecontacto;
    }
    
    public void setNombrecontacto(String nombrecontacto) {
        this.nombrecontacto = nombrecontacto;
    }
    public Integer getTelefonocontacto() {
        return this.telefonocontacto;
    }
    
    public void setTelefonocontacto(Integer telefonocontacto) {
        this.telefonocontacto = telefonocontacto;
    }
    public Long getRuc() {
        return this.ruc;
    }
    
    public void setRuc(Long ruc) {
        this.ruc = ruc;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set getProductoxproveedors() {
        return this.productoxproveedors;
    }
    
    public void setProductoxproveedors(Set productoxproveedors) {
        this.productoxproveedors = productoxproveedors;
    }
    public Set getCompras() {
        return this.compras;
    }
    
    public void setCompras(Set compras) {
        this.compras = compras;
    }




}


