package modelos;
// Generated 17-nov-2013 13:30:35 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoproducto generated by hbm2java
 */
public class Tipoproducto  implements java.io.Serializable {


     private int idtipoproducto;
     private String nombre;
     private String descripcion;
     private Set productos = new HashSet(0);

    public Tipoproducto() {
    }

	
    public Tipoproducto(int idtipoproducto) {
        this.idtipoproducto = idtipoproducto;
    }
    public Tipoproducto(int idtipoproducto, String nombre, String descripcion, Set productos) {
       this.idtipoproducto = idtipoproducto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.productos = productos;
    }
   
    public int getIdtipoproducto() {
        return this.idtipoproducto;
    }
    
    public void setIdtipoproducto(int idtipoproducto) {
        this.idtipoproducto = idtipoproducto;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set productos) {
        this.productos = productos;
    }




}


